name: Shell Quality

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck

      - name: Set up Go for shfmt
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Run shellcheck
        run: |
          set -e
          echo "Running shellcheck..."
          find . -type f -name "*.sh" -print0 | xargs -0 -I{} bash -lc 'shellcheck -x "{}"'

      - name: Run shfmt diff
        run: |
          set -e
          echo "Running shfmt..."
          shfmt -d .

